printWidth: 120
singleQuote: true
tabWidth: 2
trailingComma: all
arrowParens: avoid
endOfLine: auto

overrides:
  - files:
      - '*.js'
      - '*.ts'
      - '*.tsx'
    options:
      tabWidth: 4
